# Generated by Django 5.1.6 on 2025-03-07 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_canalum_jugno_kalumbuyan'),
        ('app1', '0002_sensor'),
    ]

    operations = [
    ]
