# Generated by Django 5.1.6 on 2025-03-07 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_merge_0002_canalum_jugno_kalumbuyan_0002_sensor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Canalumtest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('data', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Canalum',
        ),
        migrations.DeleteModel(
            name='Jugno',
        ),
        migrations.DeleteModel(
            name='Kalumbuyan',
        ),
        migrations.DeleteModel(
            name='Sensor',
        ),
        migrations.AlterField(
            model_name='bywntest',
            name='data',
            field=models.FloatField(),
        ),
    ]
