# Generated by Django 5.1.6 on 2025-03-17 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_canalumtest_delete_canalum_delete_jugno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jugnotest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('data', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Kalumbuyantest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('data', models.FloatField()),
            ],
        ),
    ]
