# Generated by Django 5.1.6 on 2025-03-17 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_jugnotest_kalumbuyantest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Jugnotest',
        ),
        migrations.DeleteModel(
            name='Kalumbuyantest',
        ),
    ]
