# Generated by Django 5.1.6 on 2025-03-19 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_delete_jugnotest_delete_kalumbuyantest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jugnotest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('data', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Kalumbuyantest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('data', models.FloatField()),
            ],
        ),
    ]
